# Generated by Django 5.1.5 on 2025-01-31 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_done", "-created_at"]},
        ),
    ]
