# Generated by Django 5.1.5 on 2025-01-31 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elements", "0002_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_done", "created_at"]},
        ),
    ]
